version: '3'

services:
  postgres:
    image: postgres
    restart: always
    build: 
      context: .
      dockerfile: Dockerfile
    environment:
      - POSTGRES_DB=mydatabase
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=1234
    ports:
      - "5433:5432"

  app:
    build: .
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - "postgres"
    environment:
      - FLASK_APP=app.py
      - FLASK_RUN_HOST=0.0.0.0
      - DATABASE_URL=postgresql://myuser:1234@localhost:5432/mydatabase
